export const abitColumnConfig: any[] = [
	{
		dataField: 'applicationCode',
		caption: 'ID заявления',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'pk',
		caption: 'Подразделение',
		width: 70,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'company',
		caption: 'Компания',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'fullName',
		caption: 'ФИО',
		width: 270,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'recruitmentYear',
		caption: 'Год набора',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'specialtyName',
		caption: 'Название специальности',
		width: 200,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'faculty',
		caption: 'Факультет',
		width: 180,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'educationForm',
		caption: 'Форма обучения',
		width: 120,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'original',
		caption: 'Оригинал',
		width: 130,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'boolean',
	},
	{
		dataField: 'priority',
		caption: 'Приоритет',
		width: 90,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'email',
		caption: 'E-mail',
		width: 250,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'mobile',
		caption: 'Мобильный',
		width: 150,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'applicationStatus',
		caption: 'Статус Абитуриента',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'studentStatus',
		caption: 'Статус Заявления',
		width: 150,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'learningConditions',
		caption: 'Условия обучения',
		width: 150,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'additionalSet',
		caption: 'Дополнительный набор',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'boolean',
	},
	{
		dataField: 'planNabora',
		caption: 'План набора',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'originalType',
		caption: 'Вид оригинала',
		width: 150,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'avgAttestatScore',
		caption: 'Средний балл аттестат',
		width: 80,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},

	{
		dataField: 'total',
		caption: 'Баллы ЕГЭ',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'ballId',
		caption: 'Баллы за индивидуальные',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'scoreSum',
		caption: 'Σ баллов + ид',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'agreement',
		caption: 'Согласие',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'boolean',
	},
	{
		dataField: 'avgEge',
		caption: 'Средний балл ЕГЭ',
		width: 80,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'consentFilesCount',
		caption: 'Согласие файлов',
		width: 50,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'greenWaveFilesCount',
		caption: 'Зелёная волна файлы',
		width: 50,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'reductionFilesCount',
		caption: 'Снижение файлов',
		width: 50,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'contractNumber',
		caption: 'Номер договора',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'contractDate',
		caption: 'Дата договора',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'date',
	},
	
	
	
	
	
	
	
	
	
	
	{
		dataField: 'costs',
		caption: 'Начислено',
		width: 100,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'sum',
		caption: 'Оплачено',
		width: 100,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	}, 
	{
		dataField: 'enrolled',
		caption: 'Зачислен',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'boolean',
	},
	{
		dataField: 'lastName',
		caption: 'Фамилия',
		width: 120,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'firstName',
		caption: 'Имя',
		width: 120,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'middleName',
		caption: 'Отчество',
		width: 120,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
]
