export const crmConfig: any[] = [
  {
    dataField: "lastName",
    caption: "Фамилия",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "firstName",
    caption: "Имя",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "middleName",
    caption: "Отчество",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "messageText",
    caption: "Сообщение",
    width: 480,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "birthDate",
    caption: "Дата рождения",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "date",
    format: "dd.MM.yyyy",
  },
  {
    dataField: "gender",
    caption: "Пол",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "operatorName",
    caption: "Оператор",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "messageDate",
    caption: "Дата сообщения",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "date",
    format: "dd.MM.yyyy",
  },
  {
    dataField: "messageIsRead",
    caption: "Прочитано",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "boolean",
  },
  {
    dataField: "lastReplyDate",
    caption: "Дата последнего ответа",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "lastMessageIsOperatorReply",
    caption: "Ответили",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "boolean",
  },
  {
    dataField: "daysFromLast",
    caption: "Дней с последнего сообщения",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "email",
    caption: "email",
    width: 150,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "mobile",
    caption: "Мобильный",
    width: 150,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "applicantId",
    caption: "Код абитуриента",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
];
