export const disciplineConfig: any[] = [
  {
    dataField: "subdivision",
    caption: "Подразделение",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "discipline",
    caption: "Испытание",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "okso",
    caption: "ОКСО",
    width: 90,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "fullName",
    caption: "ФИО",
    width: 150,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "egeYear",
    caption: "Год ЕГЭ",
    width: 70,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "score",
    caption: "Балл",
    width: 70,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "status",
    caption: "Статус",
    width: 110,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "examDate",
    caption: "Дата сдачи",
    width: 70,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "basis",
    caption: "Основания",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "submitDate",
    caption: "Дата подачи",
    width: 150,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "date",
    format: "dd.MM.yyyy",
  },
  {
    dataField: "gender",
    caption: "Пол",
    width: 70,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "studyForm",
    caption: "Форма",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "abi",
    caption: "Абитуриент",
    width: 80,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "birthDate",
    caption: "Дата рождения",
    width: 120,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "date",
    format: "dd.MM.yyyy HH:mm:ss",
  },
  {
    dataField: "mobile",
    caption: "Мобильный",
    width: 200,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
];
