
export const disciplineEntityConfig: any[] = [
  { id: 1, name: "Математика", code: "MATH", description: "Дисциплина математики" },
  { id: 2, name: "Физика", code: "PHYS", description: "Дисциплина физики" },
  { id: 3, name: "Химия", code: "CHEM", description: "Дисциплина химии" },
  { id: 4, name: "Русский язык", code: "RUSS", description: "Дисциплина русского языка" },
  { id: 5, name: "Иностранный язык", code: "LANG", description: "Дисциплина иностранного языка" },
  { id: 6, name: "Информатика", code: "INFO", description: "Дисциплина информатики" },
  { id: 7, name: "Обществознание", code: "SOC", description: "Дисциплина обществознания" },
  { id: 8, name: "История", code: "HIST", description: "Дисциплина истории" },
  { id: 9, name: "Биология", code: "BIOL", description: "Дисциплина биологии" },
  { id: 10, name: "География", code: "GEOG", description: "Дисциплина географии" }
];

export const disciplineColumnConfig: any[] = [
  {
    dataField: "id",
    caption: "ID",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "number",
  },
  {
    dataField: "studentFullName",
    caption: "ФИО Студента",
    width: 200,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "string",
  },
  {
    dataField: "disciplineName",
    caption: "Дисциплина",
    width: 150,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "string",
  },
  {
    dataField: "score",
    caption: "Балл",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "number",
  },
  {
    dataField: "examDate",
    caption: "Дата экзамена",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "date",
  },
  {
    dataField: "semester",
    caption: "Семестр",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "number",
  },
  {
    dataField: "year",
    caption: "Год",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "number",
  },
  {
    dataField: "instructor",
    caption: "Преподаватель",
    width: 180,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "string",
  },
  {
    dataField: "formOfControl",
    caption: "Форма контроля",
    width: 150,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "string",
  },
  {
    dataField: "creditHours",
    caption: "Часы",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    dataType: "number",
  }
];
