export const documentsColumnsConfig: any[] = [
	{
		dataField: 'id',
		caption: 'ID',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'documentCode',
		caption: 'Код документа',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'discipline',
		caption: 'Дисциплина',
		width: 150,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'score',
		caption: 'Баллы',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'number',
	},
	{
		dataField: 'status',
		caption: 'Статус',
		width: 150,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'documentType',
		caption: 'Тип документа',
		width: 200,
		alignment: 'left',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'fileCaption',
		caption: 'Описание файла',
		width: 200,
		alignment: 'start',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'documentSerial',
		caption: 'Серия документа',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'documentNumber',
		caption: 'Номер документа',
		width: 100,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},

	{
		dataField: 'dateOfChange',
		caption: 'Дата изменения',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'date',
	},
	{
		dataField: 'year',
		caption: 'Год',
		width: 70,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
	{
		dataField: 'guid',
		caption: 'GUID',
		width: 120,
		alignment: 'center',
		allowFiltering: true,
		allowHeaderFiltering: true,
		allowSorting: true,
		dataType: 'string',
	},
]
