export const screenConfig: any[] = [
  {
    dataField: "pcName",
    caption: "ПК",
    width: 200,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "specialtyCode",
    caption: "Код специальности",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "specialtyName",
    caption: "Название специальности",
    width: 150,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "specialtySpecialName",
    caption: "Название специализации",
    width: 250,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "okso",
    caption: "ОКСО",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "budgetPlaces",
    caption: "Бюджетные места",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "budgetAgreements",
    caption: "Договоры на бюджет",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "budgetAgreementsMinusPlaces",
    caption: "Разница (договоры - места)",
    width: 140,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "budgetAgreementsOriginal",
    caption: "Оригиналы на бюджет",
    width: 130,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "budgetAgreementsOriginalMinusPlaces",
    caption: "Разница (оригиналы - места)",
    width: 150,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "kvPlaces",
    caption: "Квота места",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "kvAgreements",
    caption: "Договоры на квоту",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "kvAgreementsMinusPlaces",
    caption: "Разница (квота)",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "kvAgreementsOriginal",
    caption: "Оригиналы на квоту",
    width: 130,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "kvAgreementsOriginalMinusPlaces",
    caption: "Разница (оригиналы - места) квота",
    width: 170,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "minobrPlaces",
    caption: "Минобр места",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "minobrAgreements",
    caption: "Договоры минобр",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "minobrAgreementsMinusPlaces",
    caption: "Разница (минобр)",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "minobrAgreementsOriginal",
    caption: "Оригиналы минобр",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "minobrAgreementsOriginalMinusPlaces",
    caption: "Разница (оригиналы - места) минобр",
    width: 170,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "cnPlaces",
    caption: "Целевое обучение места",
    width: 140,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "cnAgreements",
    caption: "Договоры целевое",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "cnAgreementsMinusPlaces",
    caption: "Разница (целевое)",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "cnAgreementsOriginal",
    caption: "Оригиналы целевое",
    width: 130,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "cnAgreementsOriginalMinusPlaces",
    caption: "Разница (оригиналы - места) целевое",
    width: 180,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "snPlaces",
    caption: "Специальный набор обучение места",
    width: 140,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "snAgreements",
    caption: "Специальный набор договоры",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "snAgreementsMinusPlaces",
    caption: "Специальный набор разница",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "snAgreementsOriginal",
    caption: "Специальный набор оригиналы",
    width: 130,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "snAgreementsOriginalMinusPlaces",
    caption: "Специальный набор разница (оригиналы - места)",
    width: 180,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "number",
  },
  {
    dataField: "educationLevel",
    caption: "Уровень образования",
    width: 120,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "educationForm",
    caption: "Форма обучения",
    width: 120,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
  {
    dataField: "educationFormCode",
    caption: "Код формы обучения",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    dataType: "string",
  },
];
