export const screenDetailGridConfig: any[] = [
  {
    dataField: "id",
    caption: "ID",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: false, 
  },
  {
    dataField: "applicationCode",
    caption: "Код заявления",
    dataType: "number",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: false, 
  },
  {
    dataField: "fullName",
    caption: "ФИО",
    dataType: "string",
    width: 250,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "specialtyCode",
    caption: "Код специальности",
    dataType: "number",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: false, 
  },
  {
    dataField: "examScore1",
    caption: "Балл 1",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "examScore2",
    caption: "Балл 2",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "examScore3",
    caption: "Балл 3",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "examScore4",
    caption: "Балл 4",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "examScore5",
    caption: "Балл 5",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "examScore6",
    caption: "Балл 6",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "totalScore",
    caption: "Общий балл",
    dataType: "number",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Общая сумма: {0}",
  },
  {
    dataField: "ballId",
    caption: "Баллы за индивидуальные",
    dataType: "number",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Сумма: {0}",
  },
  {
    dataField: "scoreSum",
    caption: "Сумма баллов",
    dataType: "number",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "sum",
    format: "#,##0",
    displayFormat: "Итого: {0}",
  },
  
  {
    dataField: "pp",
    caption: "Паспорт",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  
  {
    dataField: "admissionConsent",
    caption: "Согласие на зачисление",
    dataType: "boolean",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Кол-во: {0}",
  },
  
  {
    dataField: "disc1",
    caption: "Дисциплина 1",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "disc2",
    caption: "Дисциплина 2",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "disc3",
    caption: "Дисциплина 3",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "disc4",
    caption: "Дисциплина 4",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "disc5",
    caption: "Дисциплина 5",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "examType1",
    caption: "Тип экзамена 1",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "examType2",
    caption: "Тип экзамена 2",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "examType3",
    caption: "Тип экзамена 3",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "examType4",
    caption: "Тип экзамена 4",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "examType5",
    caption: "Тип экзамена 5",
    dataType: "string",
    width: 100,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "rankNumber",
    caption: "Ранг",
    dataType: "number",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "avg",
    format: "#,##0",
    displayFormat: "Средний ранг: {0}",
  },
  
  {
    dataField: "dormitory",
    caption: "Общежитие",
    dataType: "boolean",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Нуждающихся: {0}",
  },
  {
    dataField: "isBudget",
    caption: "Бюджет",
    dataType: "boolean",
    width: 80,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Бюджетников: {0}",
  },
  {
    dataField: "isPaidSn",
    caption: "Платное СН",
    dataType: "boolean",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Платников СН: {0}",
  },
  {
    dataField: "isTargetCn",
    caption: "Целевое ЦН",
    dataType: "boolean",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Целевиков: {0}",
  },
  {
    dataField: "isQuotaKv",
    caption: "Квота КВ",
    dataType: "boolean",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Квота: {0}",
  },
  {
    dataField: "isMinobr",
    caption: "Минобр",
    dataType: "boolean",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "Минобр: {0}",
  },
  {
    dataField: "mobilePhone",
    caption: "Мобильный телефон",
    dataType: "string",
    width: 150,
    alignment: "left",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  {
    dataField: "priority",
    caption: "Приоритет",
    dataType: "number",
    width: 90,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "avg",
    format: "#,##0",
    displayFormat: "Средний приоритет: {0}",
  },
  {
    dataField: "caseNumber",
    caption: "Номер дела",
    dataType: "string",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
  },
  
  {
    dataField: "hasOriginal",
    caption: "Есть оригинал",
    dataType: "boolean",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "С оригиналами: {0}",
  },
  {
    dataField: "hasAgreementAndOriginal",
    caption: "Согласие и оригинал",
    dataType: "boolean",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "С согласием и оригиналом: {0}",
  },
  {
    dataField: "trainingType",
    caption: "Тип обучения",
    dataType: "number",
    width: 100,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: false, 
  },
  {
    dataField: "hasAgreement",
    caption: "Есть соглашение",
    dataType: "boolean",
    width: 120,
    alignment: "center",
    allowFiltering: true,
    allowHeaderFiltering: true,
    allowSorting: true,
    allowSummary: true,
    summaryType: "count",
    displayFormat: "С соглашениями: {0}",
  },
];
